# Libraries in Python

1.  NumPy
2.  Pandas
3.  Matplotlib
4.  Seaborn


Python libraries is a collection of functions and methods that allows you to perform many actions without writing your code.

# NumPy


NumPy stands for numerical Python and it is the core library for numeric and scientific computing.      It consist of multi-dimensional array objects and a collection of routiens for processing those array.

# Why Use NumPy ?


Numpy   ( short for Numerical Python)  provides an efficient interface to store and operate on dense data buffers. in some ways ,NumPy arrays are like Python's built in list type, but NumPy arrays provide much more efficient storage and data operations as thearrays grow larger in size.

NumPy is usually imported under the np alias.

alias: In Python alias are an alternate name for referring to the same thing.

In [1]:
#The version string is stored under __version__ attribute.
import numpy as np

print(np.__version__)

1.19.2


In [10]:
import numpy as np

Single dimensional array

In [15]:
l1=([10,20,30,40,50])
l1


[10, 20, 30, 40, 50]

In [16]:
x=np.array(l1)

In [18]:
x

array([10, 20, 30, 40, 50])

In [19]:
type(x)

numpy.ndarray

Multi-dimensional array

In [22]:
l1=([[10,20,30,40,50],[60,70,80,90,100]])
l1

[[10, 20, 30, 40, 50], [60, 70, 80, 90, 100]]

In [23]:
y=np.array(l1)

In [24]:
y

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [25]:
type(y)

numpy.ndarray

Initializing NumPy array with zeros

In [28]:
import numpy as np

In [29]:
x=np.zeros((1,2))

In [30]:
x

array([[0., 0.]])

In [31]:
y=np.zeros((5,8))

In [32]:
y

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [33]:
type(y)

numpy.ndarray

Initializing NumPy array with same number    (Use Full Method for Same Number)

In [42]:
import numpy as np

In [43]:
x=np.full((2,3),88)

In [44]:
x

array([[88, 88, 88],
       [88, 88, 88]])

In [49]:
y=np.full((2,3),786)


In [50]:
y

array([[786, 786, 786],
       [786, 786, 786]])

Initializing NumPy array within a range

In [51]:
import numpy as np

In [52]:
x=np.arange(10,101)

In [53]:
x

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [54]:
y=np.arange(10,101,5)

In [55]:
y

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [56]:
y1=np.arange(50,500,10)

In [57]:
y1

array([ 50,  60,  70,  80,  90, 100, 110, 120, 130, 140, 150, 160, 170,
       180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300,
       310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410, 420, 430,
       440, 450, 460, 470, 480, 490])

Initializing NumPy array with random, numbers

In [59]:
import numpy as np

In [60]:
x=np.random.randint(100,200,10)

In [61]:
x

array([122, 105, 122, 129, 118, 160, 194, 174, 119, 175])

In [62]:
y=np.random.randint(100,200,10)

In [63]:
y

array([160, 163, 122, 189, 197, 181, 121, 155, 122, 115])

Chacking the shape of NumPy arrays

In [64]:
import numpy as np

In [65]:
x=np.array([[1,2,3,4,5],[5,4,3,2,1]])

In [66]:
x

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [70]:
x.shape=(2,5)

In [71]:
x

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [75]:
x.shape=(5,2)

In [76]:
x

array([[1, 2],
       [3, 4],
       [5, 5],
       [4, 3],
       [2, 1]])

In [80]:
x.shape=(10,1)

In [81]:
x

array([[1],
       [2],
       [3],
       [4],
       [5],
       [5],
       [4],
       [3],
       [2],
       [1]])

Join NumPy arrays

vstack()                hstack()               column_stack()

In [82]:
n1=np.array([1,2,3])
n2=np.array([4,5,6])

In [83]:
n1,n2

([1, 2, 3], [4, 5, 6])

In [84]:
np.vstack((n1,n2))

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
np.vstack((n2,n1))

array([[4, 5, 6],
       [1, 2, 3]])

In [88]:
np.hstack((n1,n2))

array([1, 2, 3, 4, 5, 6])

In [89]:
np.column_stack((n1,n2))

array([[1, 4],
       [2, 5],
       [3, 6]])

Intersection    (common value)   &    Difference 

In [126]:
n1=np.array([10,20,30,40,50])
n2=np.array([40,50,60,70,80])

In [127]:
# means common elements
x=np.intersect1d(n1,n2)           

In [128]:
x

array([40, 50])

In [129]:
# means uncommon elements
x=np.setdiff1d(n1,n2)

In [130]:
x

array([10, 20, 30])

In [131]:
x=np.intersect1d(n2,n1)

In [132]:
x

array([40, 50])

In [133]:
x=np.setdiff1d(n2,n1)

In [134]:
x

array([60, 70, 80])

# NumPy Array Mathematics

Addition of numpy array

In [118]:
import numpy as np

In [119]:
x=np.array([10,20])
y=np.array([30,40])

z=np.sum((x,y))

In [121]:
z

100

In [122]:
z=np.sum([x,y],axis=0)

In [123]:
z

array([40, 60])

In [124]:
z=np.sum([x,y],axis=1)

In [125]:
z

array([30, 70])

Basic Addition

In [136]:
x=np.array([10,20,30,40,50])
x

array([10, 20, 30, 40, 50])

In [137]:
z=x+5
z

array([15, 25, 35, 45, 55])

Basic Substraction

In [138]:
z=x-5
z

array([ 5, 15, 25, 35, 45])

Basic Multiplication

In [139]:
z=x*5
x

array([10, 20, 30, 40, 50])

Basic Division

In [145]:
z=x/5
z

array([ 2.,  4.,  6.,  8., 10.])

# NumPy Math Functions

Mean value

In [149]:
x=np.random.randint(1,100,10)
x

array([27, 21, 77, 66,  6, 61, 75, 43, 79, 67])

In [150]:
y=np.mean(x)
y

52.2

Median value

In [151]:
y=np.median(x)
y

63.5

Standard Deviation     (std)

In [153]:
y=np.std(x)
y

24.834653208772615

In [158]:
z=np.array([10,20,30,40,50,60,70,80,90])
z

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [159]:
np.mean(z)

50.0

In [160]:
np.median(z)

50.0

In [161]:
np.std(z)

25.81988897471611

# NumPy Save & Load

Saving NumPy array

In [162]:
z=np.array([10,20,30,40,50,60,70,80,90])
z

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [163]:
np.save('my_numpy',z)

Loading NumPy array

In [166]:
new=np.load('my_numpy.npy')           # .npy is stransfer numpy array

In [167]:
new

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# NumPy Class Practice

In [1]:
import numpy as np

Single Dimensional Array

In [2]:
x=np.array([3,33,333])
x

array([  3,  33, 333])

In [3]:
type(x)

numpy.ndarray

In [5]:
x.shape

(3,)

In [6]:
print(x[0],x[1],x[2])

3 33 333


In [7]:
x[0]=786
x

array([786,  33, 333])

In [8]:
x[2]=777
x

array([786,  33, 777])

Two-Dimensional Array

In [11]:
y=np.array([[11,12,13],[21,22,23]])
y

array([[11, 12, 13],
       [21, 22, 23]])

In [12]:
np.vstack(y)

array([[11, 12, 13],
       [21, 22, 23]])

In [13]:
y.shape

(2, 3)

In [21]:
print(y [0,0], y [0,1], y [0,2])

11 12 13


In [22]:
print(y [1,0], y [1,1], y [1,2])

21 22 23


In [23]:
print(y [0,0], y [0,1], y [1,2])

11 12 23


# Functions

In [28]:
z=np.zeros((3,2))
z

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [29]:
z=np.full((3,2),786)
z

array([[786, 786],
       [786, 786],
       [786, 786]])

In [34]:
z=np.eye(5,5)
z

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
z=np.ones((2,3))
z

array([[1., 1., 1.],
       [1., 1., 1.]])

In [41]:
z.shape

(2, 3)

In [48]:
z[0,0]
z

array([[1., 1., 1.],
       [1., 1., 1.]])

In [58]:
w=np.random.randint(5,50,5)
w


array([15, 32,  9, 22, 20])

In [60]:
w=np.random.random((5,3))
w


array([[0.63449626, 0.10109218, 0.94936078],
       [0.2474211 , 0.28294533, 0.79602924],
       [0.49986816, 0.86558966, 0.19282653],
       [0.37620744, 0.05930988, 0.67063128],
       [0.56935211, 0.65173081, 0.81918628]])

In [61]:
p = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
p

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

# Slicing


Slicing/Indexing using double bracket notation       a[0] [0]

Slicing/Indexing using single bracket notation       a [0,0]

In [62]:
import numpy as np

In [229]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

a [row range , column range]

In [64]:
a[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
a[1:2]

array([[4, 5, 6]])

In [69]:
a[:2, 1:3]

array([[2, 3],
       [5, 6]])

In [70]:
b=a[:2, 1:3]
b

array([[2, 3],
       [5, 6]])

In [96]:
import numpy as np
np.random.seed(111)
x=np.random.randint(1,500,30).reshape(6,5)
x

array([[341, 365, 469, 213,  87],
       [276, 170, 323, 119, 467],
       [297, 456, 442,   8, 269],
       [267, 450, 369, 217, 285],
       [271, 419,  22,  55, 201],
       [ 38, 461, 231, 187, 269]])

In [99]:
x[:2]

array([[341, 365, 469, 213,  87],
       [276, 170, 323, 119, 467]])

In [101]:
x[:2,0:2]

array([[341, 365],
       [276, 170]])

In [105]:
x[:2,2:]

array([[469, 213,  87],
       [323, 119, 467]])

In [106]:
# do the size of this value
# 369,217,285
#22,55,201

In [110]:
x[3:5,2:]

array([[369, 217, 285],
       [ 22,  55, 201]])

In [128]:
import numpy as np

In [129]:
a1 = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
a1

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [130]:
h=a1[0:2,1:3]
h

array([[12, 13],
       [22, 23]])

In [131]:
print('befor:',a1[0,1])
h[0,0]=1000
print('after:',a1[0,1])

befor: 12
after: 1000


In [133]:
a2 = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
a2

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [136]:
r1=a2[1 ]
print(r1,r1.shape)

[21 22 23 24] (4,)


In [137]:
r1=a2[1 , : ]
print(r1,r1.shape)

[21 22 23 24] (4,)


In [138]:
r2=a2[1:2, :]
print(r2,r2.shape)

[[21 22 23 24]] (1, 4)


In [139]:
r1=a2[: , 1]
r2=a2[: , 1:2]
print(r1,r1.shape)
print()
print(r2,r2.shape)

[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


In [169]:
a3=np.array([[11,12,13],[21,22,23],[31,32,33]])
a3

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [179]:
col_indices=np.array([0,1,2])
print('col indices',col_indices)

row_indices=np.arange(3)
print('row indices',row_indices)

col indices [0 1 2]
row indices [0 1 2]


In [180]:
col_indices=np.array([0,1,2])
print('col indices:',col)

row_indices=np.arange(3)
print('row indices:',row_indices)

col indices: 2
row indices: [0 1 2]


In [181]:
col_indices=np.array([0,1,2])
print('col indices:',col_indices)

row_indices=np.arange(4)
print('row indices:',row_indices)

col indices: [0 1 2]
row indices: [0 1 2 3]


In [183]:
col_indices=np.array([0,1,2])
print('col indices:',col_indices)

row_indices=np.arange(3)
print('row indices:',row_indices)

col indices: [0 1 2]
row indices: [0 1 2]


In [184]:
for row ,col in zip(row_indices,col_indices):
    print(row,",",col)
    

0 , 0
1 , 1
2 , 2


In [185]:
print('Values in array at those indices', a3[row_indices, col_indices])

Values in array at those indices [11 22 33]


In [193]:
a3[row_indices,col_indices] += 1000
a3


array([[2011,   12,   13],
       [  21, 2022,   23],
       [  31,   32, 2033]])

# Filtering


In [211]:
an_array2=np.array([[11,12],[21,22],[31,32]])
an_array2

array([[11, 12],
       [21, 22],
       [31, 32]])

In [212]:
filter1=(an_array2 > 15)
filter1

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [213]:
an_array2[filter1]

array([21, 22, 31, 32])

In [214]:
an_array2[an_array2 > 15]

array([21, 22, 31, 32])

In [220]:
an_array2[an_array2% 2==0] +=1000
an_array2

array([[  11, 4012],
       [  21, 4022],
       [  31, 4032]])

# Data Types

Int    ,    Float    ,     String   ,      boolean

In [221]:
import numpy as nps

In [222]:
ex1 = np.array([11,12])
print(ex1.dtype)

int32


In [223]:
ex2 = np.array([11.0,12.0])
print(ex2.dtype)

float64


In [224]:
ex3 = np.array([11,21], dtype=np.int64)
print(ex3.dtype)

int64


In [225]:
ex4 = np.array([11.1,12.7], dtype = np.int64)
print(ex4)
print(ex4.dtype)

[11 12]
int64


ex5 = np.array([11,21], dtype = np.float64)
print(ex5)
print(ex5.dtype)

# Arithmetic Array Operations

In [230]:
x=np.array([[111,112],[121,122]])
y=np.array([[211.1,212.1],[211.1,222.1]])

print(x)
print(y)

[[111 112]
 [121 122]]
[[211.1 212.1]
 [211.1 222.1]]


Addition

In [231]:
print(x+y)
print()

[[322.1 324.1]
 [332.1 344.1]]



In [232]:
print(np.add(x,y))

[[322.1 324.1]
 [332.1 344.1]]


Subtract

In [233]:
print(x-y)
print()

[[-100.1 -100.1]
 [ -90.1 -100.1]]



In [234]:
print(np.subtract(x,y))

[[-100.1 -100.1]
 [ -90.1 -100.1]]


Multiply

In [235]:
print(x*y)
print()

[[23432.1 23755.2]
 [25543.1 27096.2]]



In [237]:
print(np.multiply(x,y))

[[23432.1 23755.2]
 [25543.1 27096.2]]


Divide

In [238]:
print(x,y)
print()

[[111 112]
 [121 122]] [[211.1 212.1]
 [211.1 222.1]]



In [239]:
print(np.divide(x,y))

[[0.52581715 0.52805281]
 [0.57318806 0.54930212]]


Square root

In [240]:
print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


Expotential

In [241]:
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


# Basic Statistical Operation

In [254]:
arr= 10* np.random.rand(2,2)
arr

array([[1.19716918, 2.35348277],
       [3.71979655, 8.48802856]])

In [255]:
arr.mean()

3.9396192632633302

Mean along with row

In [256]:
arr.mean(axis=0)

array([2.45848286, 5.42075566])

In [257]:
np.median(arr,axis=1)

array([1.77532597, 6.10391255])

In [258]:
arr.sum()

15.758477053053321

# Sorting

In [262]:
unsorted=np.random.rand(10)
unsorted

array([0.68233651, 0.88419468, 0.81372284, 0.70713231, 0.35090865,
       0.92682985, 0.62817397, 0.5909981 , 0.6724083 , 0.6382349 ])

Create copy and sort

In [263]:
sorted=np.array(unsorted)
sorted.sort()

print(sorted)
print() 
print(unsorted)

[0.35090865 0.5909981  0.62817397 0.6382349  0.6724083  0.68233651
 0.70713231 0.81372284 0.88419468 0.92682985]

[0.68233651 0.88419468 0.81372284 0.70713231 0.35090865 0.92682985
 0.62817397 0.5909981  0.6724083  0.6382349 ]


Inplace sort

In [264]:
unsorted.sort()

print(unsorted)

[0.35090865 0.5909981  0.62817397 0.6382349  0.6724083  0.68233651
 0.70713231 0.81372284 0.88419468 0.92682985]


# Finding unique elements

In [265]:
a=np.array([1,23,4,5,51,5,5])
a

array([ 1, 23,  4,  5, 51,  5,  5])

In [266]:
np.unique(a)

array([ 1,  4,  5, 23, 51])

In [268]:
s1 = np.array(['desk', 'chair', 'bulb'])
s2 = np.array(['lamp', 'bulb', 'chair'])

In [269]:
np.intersect1d(s1,s2)

array(['bulb', 'chair'], dtype='<U5')

In [270]:
np.union1d(s1,s2)

array(['bulb', 'chair', 'desk', 'lamp'], dtype='<U5')

In [271]:
np.setdiff1d(s1,s2)

array(['desk'], dtype='<U5')

In [272]:
np.in1d(s1,s2)

array([False,  True,  True])

# Broadcasting


In [273]:
start =np.zeros((4,3))
start

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [276]:
add_rows=np.array([1,0,2])

Add to each row

In [278]:
y=start+add_rows
y

array([[1., 0., 2.],
       [1., 0., 2.],
       [1., 0., 2.],
       [1., 0., 2.]])

Transpose

In [280]:
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T  
add_cols

array([[0],
       [1],
       [2],
       [3]])

Add to each column

In [282]:
z=start +add_cols
z

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [284]:
add_scalar = np.array([5])
start + add_scalar

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [285]:
arrA = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arrA


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [286]:
arrB = [0,1,0,2]
arrB

[0, 1, 0, 2]

In [287]:
arrA + arrB

array([[ 1,  3,  3,  6],
       [ 5,  7,  7, 10],
       [ 9, 11, 11, 14]])

# Speed Test - Array vs List


In [297]:
from numpy import arange
from timeit import Timer


In [298]:
size= 1000000
timeits=1000

In [299]:
nd_array=arange(size)
type(nd_array)

numpy.ndarray

In [301]:
timer_numpy = Timer("nd_array.sum()", "from __main__ import nd_array")

print("Time taken by numpy ndarray: %f seconds" % 
      (timer_numpy.timeit(timeits)/timeits))

Time taken by numpy ndarray: 0.000800 seconds


In [302]:
a_list=list(range(size))
type(a_list)

list

In [304]:
timer_list = Timer("sum(a_list)", "from __main__ import a_list")

print("Time taken by list: %f seconds" % 
      (timer_list.timeit(timeits)/timeits))

Time taken by list: 0.044853 seconds


# Binary Format

In [305]:
x = np.array([23.23,24.24])

In [306]:
np.save('an_array', x)

In [307]:
np.load('an_array.npy')

array([23.23, 24.24])

# Text Format

In [308]:
np.savetxt('array.txt', X=x, delimiter=',')

In [309]:
np.loadtxt('array.txt', delimiter=',')

array([23.23, 24.24])

# Additional Common NDarray Operations

Dot product of two matrices

In [310]:
x2d = np.array([[1,1],[1,1]])
y2d = np.array([[2,2],[2,2]])

print(x2d.dot(y2d))
print()
print(np.dot(x2d,y2d))

[[4 4]
 [4 4]]

[[4 4]
 [4 4]]


Inner product of two vectors


In [311]:
a1d = np.array([9,9])
b1d = np.array([10,10])

print(a1d.dot(b1d))
print()
print(np.dot(a1d,b1d))

180

180


Dot product of two vectors

In [312]:
print(x2d.dot(a1d))
print()
print(np.dot(x2d,a1d))

[18 18]

[18 18]


# Sum

In [314]:
ex1 = np.array([[11,12],[21,22]])
ex1

array([[11, 12],
       [21, 22]])

In [315]:
print(np.sum(ex1))

66


Columnwise sum

In [316]:
print(np.sum(ex1, axis=0))

[32 34]


Rowwise sum

In [317]:
print(np.sum(ex1, axis=0))

[32 34]


Rowwise sum

In [318]:
print(np.sum(ex1, axis=1))

[23 43]


# Elementwise Functions

In [321]:
x = np.random.rand(8)
x

array([0.62941554, 0.53645869, 0.10915971, 0.40756546, 0.79092571,
       0.4647254 , 0.40471584, 0.12359525])

In [322]:
y = np.random.randn(8)
y

array([-2.05589845, -1.01200988, -1.88981132,  0.87190345, -0.05713844,
       -1.13473808,  0.39803292,  0.08534354])

In [323]:
np.maximum(x,y)

array([0.62941554, 0.53645869, 0.10915971, 0.87190345, 0.79092571,
       0.4647254 , 0.40471584, 0.12359525])

# Reshape

In [324]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [325]:
arr.reshape(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [326]:
ex1 = np.array([[11,12],[21,22]])
ex1

array([[11, 12],
       [21, 22]])

In [330]:
ex1.T

array([[11, 21],
       [12, 22]])

# Indexing Using Where        ()

In [331]:
x1 = np.array([1,2,3,4,5])
y1 = np.array([11,22,33,44,55])

filter = np.array([True, False,True, False,True])

In [332]:
out = np.where(filter,x1,y1)
out


array([ 1, 22,  3, 44,  5])

In [333]:
mat = np.random.rand(5,5)
mat

array([[0.41810078, 0.98648274, 0.35337821, 0.20511524, 0.91082565],
       [0.63704507, 0.69515366, 0.63024749, 0.96656555, 0.22730868],
       [0.39618962, 0.0975102 , 0.74517165, 0.56887986, 0.67030424],
       [0.37338724, 0.4711458 , 0.57076602, 0.17880649, 0.13593427],
       [0.86841593, 0.67860706, 0.40395245, 0.72797081, 0.29225478]])

if mat>0.5, replace it with 1000 else replace it with -1

In [335]:
np.where(mat>0.5 ,1000 ,-1)   

array([[  -1, 1000,   -1,   -1, 1000],
       [1000, 1000, 1000, 1000,   -1],
       [  -1,   -1, 1000, 1000, 1000],
       [  -1,   -1, 1000,   -1,   -1],
       [1000, 1000,   -1, 1000,   -1]])

# Any or All

In [336]:
arr_bools = np.array([True, False,True,True, False])

In [338]:
arr_bools.any()

True

In [339]:
arr_bools.all()

False

In [340]:
y = np.random.normal(size = (1,5))
y

array([[ 0.25399349,  2.5269756 ,  1.14425441,  2.10007727, -0.23997956]])

In [341]:
z = np.random.randint(2,50,4)
z

array([11, 25, 25, 47])

returns new ordering of elements in Z

In [342]:
np.random.permutation(z)

array([25, 47, 11, 25])

uniform distribution

In [343]:
np.random.uniform(size = 4)

array([0.59107267, 0.96630446, 0.81035082, 0.5765508 ])

normal distribution

In [344]:
np.random.normal(size = 4)

array([ 0.08926571,  0.87873723, -1.38559275,  0.96509219])

# Merging Arrays


In [345]:
k = np.random.randint(low = 2 , high = 50, size = (2,2))
k

array([[17, 24],
       [16, 30]])

In [346]:
m = np.random.randint(low = 2 , high = 50, size = (2,2))
m


array([[10, 26],
       [11, 10]])

In [347]:
np.vstack((k,m))

array([[17, 24],
       [16, 30],
       [10, 26],
       [11, 10]])

In [348]:
np.hstack((k,m))

array([[17, 24, 10, 26],
       [16, 30, 11, 10]])

axis = 0 > along column


In [349]:
np.concatenate([k,m], axis = 0)

array([[17, 24],
       [16, 30],
       [10, 26],
       [11, 10]])

axis = 1 > along row


In [351]:
np.concatenate([k,m], axis = 1)

array([[17, 24, 10, 26],
       [16, 30, 11, 10]])